version: '3.9'

services:
  cassandra:
    container_name: cassandra
    image: dps-ais/cassandra:1.0
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    hostname: cass1
    ports:
      - "9042:9042"
    volumes:
      - "./config/cassandra_local:/var/lib/cassandra"
    environment:
      CASSANDRA_CLUSTER_NAME: "demo"
      CASSANDRA_KEYSPACE: "invoicedata"
